name = "casatrack-api"
main = "src/index.ts"
compatibility_date = "2026-08-01"

[vars]
HISTORY_RETENTION_DAYS = "30"

[[d1_databases]]
binding = "DB"
database_name = "casatrack"
database_id = "76e14dbc-4986-43f6-917d-fd2fb5805e15"

[triggers]
crons = ["17 3 * * *"]
