package com.casatrack.app

import android.content.Intent
import android.graphics.BitmapFactory
import android.net.Uri
import android.os.Bundle
import android.text.InputType
import android.view.View
import android.view.ViewGroup
import android.widget.Button
import android.widget.EditText
import android.widget.LinearLayout
import android.widget.ScrollView
import android.widget.TextView
import android.widget.Toast
import androidx.activity.result.contract.ActivityResultContracts
import androidx.appcompat.app.AlertDialog
import androidx.appcompat.app.AppCompatActivity
import com.google.zxing.BinaryBitmap
import com.google.zxing.MultiFormatReader
import com.google.zxing.RGBLuminanceSource
import com.google.zxing.common.HybridBinarizer
import com.journeyapps.barcodescanner.ScanContract
import com.journeyapps.barcodescanner.ScanOptions
import org.json.JSONObject

/**
 * Entry point for fresh installs. Configured installs skip this screen.
 *
 * The stable-signing migration deliberately reuses the invitation QR generated by
 * CasaTrack 0.2.1, so an already-installed debug build does not have to be updated
 * before it can transfer its server identity to the first permanently signed build.
 */
class MigrationActivity : AppCompatActivity() {
    private lateinit var prefs: AppPrefs
    private lateinit var migration: LinearLayout
    private lateinit var recovery: LinearLayout
    private lateinit var migrationStatus: TextView
    private lateinit var api: EditText
    private lateinit var deviceId: EditText
    private lateinit var token: EditText
    private lateinit var person: EditText
    private lateinit var label: EditText

    private var transferApiUrl: String? = null
    private var transferInviteToken: String? = null

    private val qrLauncher = registerForActivityResult(ScanContract()) { result ->
        val content = result.contents
        if (content.isNullOrBlank()) toast("Escaneo cancelado") else handleTransferQr(content)
    }

    private val imageLauncher = registerForActivityResult(ActivityResultContracts.OpenDocument()) { uri ->
        if (uri != null) decodeQrImage(uri)
    }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        prefs = AppPrefs(this)
        if (prefs.configured()) {
            openMain()
            return
        }
        setContentView(buildUi())
    }

    private fun buildUi(): ScrollView {
        val density = resources.displayMetrics.density
        fun dp(v: Int) = (v * density).toInt()
        fun field(hint: String, password: Boolean = false) = EditText(this).apply {
            this.hint = hint
            if (password) inputType = InputType.TYPE_CLASS_TEXT or InputType.TYPE_TEXT_VARIATION_PASSWORD
            layoutParams = LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.WRAP_CONTENT)
        }
        fun button(text: String, click: () -> Unit) = Button(this).apply {
            this.text = text
            setOnClickListener { click() }
        }

        val root = LinearLayout(this).apply {
            orientation = LinearLayout.VERTICAL
            setPadding(dp(18), dp(24), dp(18), dp(28))
        }
        root.addView(TextView(this).apply { text = "CasaTrack"; textSize = 26f })
        root.addView(TextView(this).apply {
            text = "Configuración del teléfono"
            textSize = 16f
            setPadding(0, dp(4), 0, dp(18))
        })

        root.addView(button("Es un teléfono nuevo") { openMain() })
        root.addView(TextView(this).apply {
            text = "Agregalo normalmente con el QR de invitación de otro CasaTrack."
            textSize = 12f
            setPadding(0, 0, 0, dp(14))
        })

        root.addView(button("Migrar una instalación anterior") {
            migration.visibility = if (migration.visibility == View.VISIBLE) View.GONE else View.VISIBLE
        })

        migration = LinearLayout(this).apply {
            orientation = LinearLayout.VERTICAL
            visibility = View.GONE
            setPadding(0, dp(12), 0, dp(14))
        }
        migration.addView(TextView(this).apply {
            text = "Antes de desinstalar la versión anterior: Familia → Invitar otro teléfono → guardá una captura del QR. Después instalá esta versión y elegí esa captura. CasaTrack conservará el mismo dispositivo, historial y entidad de Home Assistant."
            textSize = 13f
        })
        migration.addView(button("Escanear QR con cámara") { scanTransferQr() })
        migration.addView(button("Elegir captura del QR") { imageLauncher.launch(arrayOf("image/*")) })
        migrationStatus = TextView(this).apply {
            text = "Esperando el QR de migración"
            setPadding(0, dp(8), 0, 0)
        }
        migration.addView(migrationStatus)
        root.addView(migration)

        root.addView(button("Recuperación manual avanzada") {
            recovery.visibility = if (recovery.visibility == View.VISIBLE) View.GONE else View.VISIBLE
        })

        recovery = LinearLayout(this).apply {
            orientation = LinearLayout.VERTICAL
            visibility = View.GONE
            setPadding(0, dp(12), 0, 0)
        }
        recovery.addView(TextView(this).apply {
            text = "Sólo si no podés usar el QR. Permite recuperar directamente los datos de una instalación de prototipo."
            textSize = 13f
        })
        api = field("Worker URL · https://...workers.dev")
        deviceId = field("ID del dispositivo anterior")
        token = field("Token del dispositivo anterior", true)
        person = field("Nombre de la persona")
        label = field("Nombre del teléfono")
        recovery.addView(api)
        recovery.addView(deviceId)
        recovery.addView(token)
        recovery.addView(person)
        recovery.addView(label)
        recovery.addView(button("Recuperar este dispositivo") { recoverManual() })
        root.addView(recovery)

        return ScrollView(this).apply { addView(root) }
    }

    private fun scanTransferQr() {
        val options = ScanOptions()
            .setDesiredBarcodeFormats(ScanOptions.QR_CODE)
            .setPrompt("Escaneá el QR de invitación CasaTrack")
            .setBeepEnabled(false)
            .setOrientationLocked(false)
        qrLauncher.launch(options)
    }

    private fun decodeQrImage(uri: Uri) {
        migrationStatus.text = "Leyendo captura…"
        Thread {
            val result = runCatching {
                val bitmap = contentResolver.openInputStream(uri).use { input ->
                    BitmapFactory.decodeStream(input) ?: error("No se pudo abrir la imagen")
                }
                val pixels = IntArray(bitmap.width * bitmap.height)
                bitmap.getPixels(pixels, 0, bitmap.width, 0, 0, bitmap.width, bitmap.height)
                val source = RGBLuminanceSource(bitmap.width, bitmap.height, pixels)
                MultiFormatReader().decode(BinaryBitmap(HybridBinarizer(source))).text
            }
            runOnUiThread {
                result.onSuccess { handleTransferQr(it) }
                    .onFailure {
                        migrationStatus.text = "No encontré un QR válido en esa imagen"
                        toast("No se pudo leer el QR")
                    }
            }
        }.start()
    }

    private fun handleTransferQr(content: String) {
        val uri = runCatching { Uri.parse(content) }.getOrNull()
        if (uri?.scheme != "casatrack" || uri.host != "enroll") {
            toast("Ese QR no es una invitación CasaTrack")
            return
        }
        val url = uri.getQueryParameter("url")?.trim()?.trimEnd('/').orEmpty()
        val invite = uri.getQueryParameter("invite")?.trim().orEmpty()
        if (!url.startsWith("https://") || invite.isBlank()) {
            toast("Invitación incompleta")
            return
        }
        transferApiUrl = url
        transferInviteToken = invite
        migrationStatus.text = "Invitación válida · buscando dispositivos…"
        inspectTransferInvite(url, invite)
    }

    private fun inspectTransferInvite(url: String, invite: String) {
        Thread {
            runCatching { FamilyClient.inspectInvite(url, invite) }
                .onSuccess { result -> runOnUiThread { showTransferChoices(result) } }
                .onFailure { err -> runOnUiThread {
                    migrationStatus.text = "La invitación no se pudo validar"
                    toast(apiError(err))
                } }
        }.start()
    }

    private fun showTransferChoices(result: JSONObject) {
        val array = result.optJSONArray("devices")
        if (array == null || array.length() == 0) {
            migrationStatus.text = "No hay dispositivos existentes para migrar"
            return
        }

        val devices = mutableListOf<JSONObject>()
        for (i in 0 until array.length()) devices += array.getJSONObject(i)
        val labels = devices.map { d ->
            val admin = if (d.optInt("is_admin", 0) == 1) " · admin" else ""
            "${d.optString("person_name", "Sin nombre")} — ${d.optString("label", "Android")}$admin"
        }.toTypedArray()

        migrationStatus.text = "Elegí qué instalación estás reemplazando"
        AlertDialog.Builder(this)
            .setTitle("Conservar dispositivo existente")
            .setItems(labels) { _, which -> confirmTransfer(devices[which]) }
            .setNegativeButton("Cancelar", null)
            .show()
    }

    private fun confirmTransfer(device: JSONObject) {
        val personName = device.optString("person_name", "Sin nombre")
        val oldLabel = device.optString("label", "Android")
        AlertDialog.Builder(this)
            .setTitle("Migrar $personName")
            .setMessage("Se conservarán el ID, historial, rol administrador y entidad de Home Assistant. El token anterior será reemplazado.")
            .setPositiveButton("Migrar") { _, _ -> transferDevice(device, oldLabel) }
            .setNegativeButton("Cancelar", null)
            .show()
    }

    private fun transferDevice(device: JSONObject, oldLabel: String) {
        val url = transferApiUrl ?: return
        val invite = transferInviteToken ?: return
        val id = device.optString("device_id")
        migrationStatus.text = "Transfiriendo identidad…"

        Thread {
            runCatching { FamilyClient.transferExisting(url, invite, id, prefs.deviceLabel.ifBlank { oldLabel }) }
                .onSuccess { result ->
                    prefs.saveEnrollment(
                        apiUrl = url,
                        deviceId = result.getString("device_id"),
                        personName = result.getString("person_name"),
                        label = result.optString("label", oldLabel),
                        token = result.getString("device_token"),
                    )
                    prefs.isAdmin = result.optBoolean("is_admin", false)
                    runOnUiThread {
                        Toast.makeText(this, "Dispositivo migrado sin cambiar su identidad", Toast.LENGTH_LONG).show()
                        openMain()
                    }
                }
                .onFailure { err -> runOnUiThread {
                    migrationStatus.text = "No se pudo completar la migración"
                    toast(apiError(err))
                } }
        }.start()
    }

    private fun recoverManual() {
        val url = api.text.toString().trim().trimEnd('/')
        val id = deviceId.text.toString().trim()
        val rawToken = token.text.toString().trim()
        val personName = person.text.toString().trim()
        val phoneLabel = label.text.toString().trim().ifBlank { "Android" }

        if (!url.startsWith("https://")) { toast("Worker URL inválida"); return }
        if (!Regex("^[A-Za-z0-9._-]{2,80}$").matches(id)) { toast("ID del dispositivo inválido"); return }
        if (rawToken.isBlank()) { toast("Falta el token del dispositivo"); return }
        if (personName.isBlank()) { toast("Falta el nombre de la persona"); return }

        prefs.saveEnrollment(url, id, personName, phoneLabel, rawToken)
        toast("Configuración recuperada")
        openMain()
    }

    private fun apiError(err: Throwable): String = when (err) {
        is CasaTrackApiException -> when (err.apiError) {
            "invite_invalid_or_expired" -> "La invitación venció o ya fue usada"
            "invite_already_used" -> "La invitación ya fue usada"
            "target_not_found" -> "Ese dispositivo ya no existe"
            else -> err.apiError
        }
        else -> err.message ?: "Error de conexión"
    }

    private fun openMain() {
        startActivity(Intent(this, MainActivity::class.java))
        finish()
    }

    private fun toast(message: String) = Toast.makeText(this, message, Toast.LENGTH_SHORT).show()
}
